# Generated by Django 4.1.3 on 2022-11-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('telephone', models.BigIntegerField(verbose_name='telephone')),
                ('email', models.CharField(max_length=30, verbose_name='email')),
            ],
        ),
    ]
